name: Publish Synr

on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install
    - name: Publish
      run: |
        poetry publish --build --username __token__ --password ${{ secrets.PYPI_API_KEY }}
